import { formatConfidence, primaryLabel } from "./image";
import type { Prediction } from "@/hooks/useImageClassifier";

export interface PdfOptions {
  predictions: Prediction[];
  thumbnail?: string; // dataURL
  modelName: string;
  inferenceMs: number | null;
  createdAt?: number;
}

// Generate and trigger download of a nicely formatted PDF result sheet.
export async function downloadPredictionsPdf(opts: PdfOptions) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 48;
  let y = 56;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("VisionAI — Classification Report", marginX, y);
  y += 22;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  const date = new Date(opts.createdAt ?? Date.now()).toLocaleString();
  doc.text(
    `Model: ${opts.modelName}   |   Time: ${opts.inferenceMs ?? "-"} ms   |   ${date}`,
    marginX,
    y,
  );
  y += 24;

  if (opts.thumbnail) {
    try {
      const imgW = 180;
      const imgH = 180;
      doc.addImage(opts.thumbnail, "JPEG", marginX, y, imgW, imgH);
      y += imgH + 20;
    } catch (err) {
      console.warn("pdf image embed failed", err);
    }
  }

  doc.setTextColor(20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Top 5 Predictions", marginX, y);
  y += 18;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  opts.predictions.forEach((p, i) => {
    const label = `${i + 1}. ${primaryLabel(p.className)}`;
    const conf = formatConfidence(p.probability);
    doc.text(label, marginX, y);
    doc.text(conf, pageWidth - marginX, y, { align: "right" });
    // confidence bar
    const barX = marginX;
    const barY = y + 6;
    const barW = pageWidth - marginX * 2;
    doc.setDrawColor(220);
    doc.setFillColor(240);
    doc.rect(barX, barY, barW, 6, "F");
    doc.setFillColor("#7a5af8");
    doc.rect(barX, barY, barW * p.probability, 6, "F");
    y += 30;
  });

  y += 10;
  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text(
    "Generated by VisionAI. Predictions ran entirely in your browser.",
    marginX,
    y,
  );

  doc.save(`visionai-report-${Date.now()}.pdf`);
}
